homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 29.8782
  longitude: 121.5495
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Shanghai
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Show the introduction message on startup.
#introduction:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
http:
  api_password: !secret http_password
# ssl config
# port forwarding in router form 8123-8123 to 8123(external)-433(internal)
#  server_port: 443
#  base_url: https://myhome-assistant.duckdns.org:8123
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

# Discover some devices automatically
discovery:

# Text to speech
tts:
  - platform: google

media_player:
  # Sony TV
  - platform: braviatv
    name: Sony Braviatv
    host: 192.168.1.10

# Xiaomi Aqara
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: 78:11:DC:B3:88:73
      key: 5r51j9lius672ywp

zone: !include zones.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
device_tracker: !include device_tracker.yaml 
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
